### ISSUE TITLE
package does not follow separation of concerns

### ISSUE THREAD

**Issue by rmnldwg** [rmnldwg/lymph#44]
Currently, the `Unilateral` class handles passing spread probabilities to the `Node` instances to help it compute its `trans_prob`. But the `Node` class should be able to do that itself based on its incoming `Edge` instances.

**Comment by rmnldwg** [comment]
To wrap this up a little more:
1. The class `Unilateral` should _request_ transition probabilities from the `Node` class, and _send_ new parameters to the `Edge` class.
2. The `Node` class should _request_ the parameters to compute its transition probability from the incoming `Edge` classes, and _send_ the computed probability to the `Unilateral` class.
3. The `Edge` class should _receive_ new spread probabilities from the `Unilateral` class, and _send_ then to the `Node` class it points to upon request.

That way, everything is nicely encapsulated and modular. For example, if we want to change the parametrization, we would only need to modify the implementation in the `Unilateral` class.

**Comment by YoelPH** [comment]
This is solved with the latest update. What has not been implemented so far is the splitting of the Node class into tumor node and LNL node (we can discuss this on Wednesday)
