### ISSUE TITLE
Bug in comp_diagnose_encoding function of unilateral

### ISSUE THREAD

**Issue by YoelPH** [rmnldwg/lymph#56]
There is an issue in the `comp_diagnose_encoding` function in [unilateral.py](https://github.com/rmnldwg/lymph/blob/main/lymph/models/unilateral.py.

in line 822 we have:
```python
                    lnls=[lnl.name for lnl in self.graph.lnls],
```
But this does not work as `self.graph.lnls` is not an object but a dictionary. Hence i propose the following fix:
```python 
                    lnls=[lnl for lnl in self.lnls.keys()],
```

**Comment by rmnldwg** [comment]
Thanks! This is fixed and tested now in the dev branch and will be merged into main with the next release.
