### ISSUE TITLE
Bug in risk comp_posterior_state_dist() in unilateral

### ISSUE THREAD

**Issue by YoelPH** [rmnldwg/lymph#57]
There is an issue in the `comp_diagnose_encoding` function in [unilateral.py](https://github.com/rmnldwg/lymph/blob/main/lymph/models/unilateral.py.

in line 876 we have:
```python
    diagnose_given_state = diagnose_encoding @ self.observation_matrix
```
This does not work as the two matrices do not have matching dimensions. After going through all the underlying code I assume that the dimensions of the `self.observation_matrix` are simply transposed. The following fix makes the function functional:
```python 
        diagnose_given_state = diagnose_encoding @ self.observation_matrix.T
```

**Comment by rmnldwg** [comment]
Good catch! I've fixed it in both the uni- and the bilateral model and added tests. The fixes live in the dev branch for now. Will be merged with the next release.
